// Sprint F — icon attribution manifest (GENERATED by web/scripts/vendor-icons.mjs; do not edit by hand).
//
// One record per icon in manifest.ts, recording exactly where it came from.
// Deliberately a separate file from manifest.ts: that file inlines every SVG
// (including two base64-encoded PNGs), and the Attributions page has no
// reason to pull that payload in just to list credits.

export type IconSource = "svgl" | "lobehub" | "inline" | "raster";

export interface IconAttribution {
  slug: string;
  source: IconSource;
  sourceFile: string; // upstream filename, or where the mark was authored/cropped from
  license: string;
  licenseUrl: string; // "" when license isn't a URL-linkable FOSS license (e.g. brand marks)
  projectUrl: string; // "" when there's no canonical project page (in-repo authored marks)
}

// Regenerated by web/scripts/vendor-icons.mjs.
export const ICON_ATTRIBUTIONS: IconAttribution[] = [
  {"slug":"aiand","source":"raster","sourceFile":"scripts/assets/aiand.png","license":"brand mark (not FOSS-licensed)","licenseUrl":"","projectUrl":"https://www.aiand.com"},
  {"slug":"alibaba","source":"lobehub","sourceFile":"alibaba-color.svg","license":"MIT","licenseUrl":"https://github.com/lobehub/lobe-icons/blob/master/LICENSE","projectUrl":"https://lobehub.com/icons"},
  {"slug":"anthropic","source":"svgl","sourceFile":"claude-ai-icon.svg","license":"MIT","licenseUrl":"https://github.com/pheralb/svgl/blob/main/LICENSE","projectUrl":"https://svgl.app"},
  {"slug":"bedrock","source":"lobehub","sourceFile":"bedrock-color.svg","license":"MIT","licenseUrl":"https://github.com/lobehub/lobe-icons/blob/master/LICENSE","projectUrl":"https://lobehub.com/icons"},
  {"slug":"carbon","source":"inline","sourceFile":"authored in vendor-icons.mjs (B/W hex+strand, 2026-08-14)","license":"in-repo","licenseUrl":"","projectUrl":"https://huggingface.co/HuggingFaceBio/Carbon-8B"},
  {"slug":"carbon8b","source":"inline","sourceFile":"authored in vendor-icons.mjs (hexagon+DNA-helix, 2026-08-14)","license":"in-repo","licenseUrl":"","projectUrl":"https://huggingface.co/HuggingFaceBio/Carbon-8B"},
  {"slug":"claude","source":"lobehub","sourceFile":"claude-color.svg","license":"MIT","licenseUrl":"https://github.com/lobehub/lobe-icons/blob/master/LICENSE","projectUrl":"https://lobehub.com/icons"},
  {"slug":"coding","source":"inline","sourceFile":"authored in vendor-icons.mjs","license":"in-repo","licenseUrl":"","projectUrl":""},
  {"slug":"comfyui","source":"lobehub","sourceFile":"comfyui-color.svg (hand-composited)","license":"MIT","licenseUrl":"https://github.com/lobehub/lobe-icons/blob/master/LICENSE","projectUrl":"https://lobehub.com/icons"},
  {"slug":"deepreinforce","source":"inline","sourceFile":"authored in vendor-icons.mjs (reinforcement loop, 2026-08-14; deepreinforce.ai is a parked domain, svgl/lobehub 404)","license":"in-repo","licenseUrl":"","projectUrl":"https://huggingface.co/deepreinforce-ai/Ornith-1.0-35B"},
  {"slug":"deepseek","source":"svgl","sourceFile":"deepseek.svg","license":"MIT","licenseUrl":"https://github.com/pheralb/svgl/blob/main/LICENSE","projectUrl":"https://svgl.app"},
  {"slug":"fireworks","source":"lobehub","sourceFile":"fireworks-color.svg","license":"MIT","licenseUrl":"https://github.com/lobehub/lobe-icons/blob/master/LICENSE","projectUrl":"https://lobehub.com/icons"},
  {"slug":"gemini","source":"svgl","sourceFile":"gemini.svg","license":"MIT","licenseUrl":"https://github.com/pheralb/svgl/blob/main/LICENSE","projectUrl":"https://svgl.app"},
  {"slug":"gemma","source":"lobehub","sourceFile":"gemma-color.svg","license":"MIT","licenseUrl":"https://github.com/lobehub/lobe-icons/blob/master/LICENSE","projectUrl":"https://lobehub.com/icons"},
  {"slug":"google","source":"svgl","sourceFile":"google.svg","license":"MIT","licenseUrl":"https://github.com/pheralb/svgl/blob/main/LICENSE","projectUrl":"https://svgl.app"},
  {"slug":"grok","source":"lobehub","sourceFile":"grok.svg","license":"MIT","licenseUrl":"https://github.com/lobehub/lobe-icons/blob/master/LICENSE","projectUrl":"https://lobehub.com/icons"},
  {"slug":"hearing","source":"inline","sourceFile":"authored in vendor-icons.mjs","license":"in-repo","licenseUrl":"","projectUrl":""},
  {"slug":"huggingscience","source":"lobehub","sourceFile":"huggingface-color.svg","license":"MIT","licenseUrl":"https://github.com/lobehub/lobe-icons/blob/master/LICENSE","projectUrl":"https://lobehub.com/icons"},
  {"slug":"hunyuan","source":"lobehub","sourceFile":"hunyuan-color.svg","license":"MIT","licenseUrl":"https://github.com/lobehub/lobe-icons/blob/master/LICENSE","projectUrl":"https://lobehub.com/icons"},
  {"slug":"long-context","source":"inline","sourceFile":"authored in vendor-icons.mjs","license":"in-repo","licenseUrl":"","projectUrl":""},
  {"slug":"meta","source":"svgl","sourceFile":"meta.svg","license":"MIT","licenseUrl":"https://github.com/pheralb/svgl/blob/main/LICENSE","projectUrl":"https://svgl.app"},
  {"slug":"microsoft","source":"svgl","sourceFile":"microsoft.svg","license":"MIT","licenseUrl":"https://github.com/pheralb/svgl/blob/main/LICENSE","projectUrl":"https://svgl.app"},
  {"slug":"mistral","source":"svgl","sourceFile":"mistral-ai_logo.svg","license":"MIT","licenseUrl":"https://github.com/pheralb/svgl/blob/main/LICENSE","projectUrl":"https://svgl.app"},
  {"slug":"moonshot","source":"svgl","sourceFile":"kimi-icon.svg","license":"MIT","licenseUrl":"https://github.com/pheralb/svgl/blob/main/LICENSE","projectUrl":"https://svgl.app"},
  {"slug":"nvidia","source":"lobehub","sourceFile":"nvidia-color.svg","license":"MIT","licenseUrl":"https://github.com/lobehub/lobe-icons/blob/master/LICENSE","projectUrl":"https://lobehub.com/icons"},
  {"slug":"openai","source":"svgl","sourceFile":"openai.svg","license":"MIT","licenseUrl":"https://github.com/pheralb/svgl/blob/main/LICENSE","projectUrl":"https://svgl.app"},
  {"slug":"openrouter","source":"lobehub","sourceFile":"openrouter-color.svg","license":"MIT","licenseUrl":"https://github.com/lobehub/lobe-icons/blob/master/LICENSE","projectUrl":"https://lobehub.com/icons"},
  {"slug":"ornith","source":"raster","sourceFile":"scripts/assets/ornith.png","license":"brand mark (not FOSS-licensed)","licenseUrl":"","projectUrl":"https://huggingface.co/deepreinforce-ai/Ornith-1.0-35B"},
  {"slug":"oss","source":"inline","sourceFile":"authored in vendor-icons.mjs","license":"in-repo","licenseUrl":"","projectUrl":""},
  {"slug":"poolside","source":"lobehub","sourceFile":"poolside-color.svg","license":"MIT","licenseUrl":"https://github.com/lobehub/lobe-icons/blob/master/LICENSE","projectUrl":"https://lobehub.com/icons"},
  {"slug":"qwen","source":"svgl","sourceFile":"qwen_light.svg","license":"MIT","licenseUrl":"https://github.com/pheralb/svgl/blob/main/LICENSE","projectUrl":"https://svgl.app"},
  {"slug":"reasoning","source":"inline","sourceFile":"authored in vendor-icons.mjs","license":"in-repo","licenseUrl":"","projectUrl":""},
  {"slug":"tencent","source":"lobehub","sourceFile":"tencent-color.svg","license":"MIT","licenseUrl":"https://github.com/lobehub/lobe-icons/blob/master/LICENSE","projectUrl":"https://lobehub.com/icons"},
  {"slug":"uncensored","source":"inline","sourceFile":"authored in vendor-icons.mjs","license":"in-repo","licenseUrl":"","projectUrl":""},
  {"slug":"vision","source":"inline","sourceFile":"authored in vendor-icons.mjs","license":"in-repo","licenseUrl":"","projectUrl":""},
  {"slug":"zhipu","source":"lobehub","sourceFile":"zhipu-color.svg","license":"MIT","licenseUrl":"https://github.com/lobehub/lobe-icons/blob/master/LICENSE","projectUrl":"https://lobehub.com/icons"},
];
