// Sprint F — software attribution manifest (GENERATED by web/scripts/gen-attributions.mjs; do not edit by hand).
//
// Regenerated automatically before every build ("npm run build" runs this
// first). npm licenses come straight from each installed package's own
// package.json. Go licenses are sniffed from the module cache's vendored
// LICENSE file against a small SPDX matcher — see gen-attributions.mjs for
// the toolchain-unavailable fallback (reuses the prior value, never
// fabricates or blanks one).

export interface NpmDep {
  name: string;
  version: string;
  license: string;
  projectUrl: string;
  direct: boolean;
}

export interface GoDep {
  path: string;
  version: string;
  indirect: boolean;
  license: string;
  projectUrl: string;
}

export interface RuntimeComponent {
  name: string;
  role: string;
  license: string;
  projectUrl: string;
}

export const NPM_DEPS: NpmDep[] = [
  {
    "name": "@tanstack/react-query",
    "version": "5.101.3",
    "license": "MIT",
    "projectUrl": "https://tanstack.com/query",
    "direct": true
  },
  {
    "name": "@types/node",
    "version": "24.13.3",
    "license": "MIT",
    "projectUrl": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node",
    "direct": false
  },
  {
    "name": "@types/react",
    "version": "19.2.17",
    "license": "MIT",
    "projectUrl": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react",
    "direct": false
  },
  {
    "name": "@types/react-dom",
    "version": "19.2.3",
    "license": "MIT",
    "projectUrl": "https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dom",
    "direct": false
  },
  {
    "name": "@vitejs/plugin-react",
    "version": "6.0.3",
    "license": "MIT",
    "projectUrl": "https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react#readme",
    "direct": false
  },
  {
    "name": "oxlint",
    "version": "1.74.0",
    "license": "MIT",
    "projectUrl": "https://oxc.rs/docs/guide/usage/linter",
    "direct": false
  },
  {
    "name": "react",
    "version": "19.2.7",
    "license": "MIT",
    "projectUrl": "https://react.dev/",
    "direct": true
  },
  {
    "name": "react-dom",
    "version": "19.2.7",
    "license": "MIT",
    "projectUrl": "https://react.dev/",
    "direct": true
  },
  {
    "name": "typescript",
    "version": "6.0.3",
    "license": "Apache-2.0",
    "projectUrl": "https://www.typescriptlang.org/",
    "direct": false
  },
  {
    "name": "vite",
    "version": "8.1.5",
    "license": "MIT",
    "projectUrl": "https://vite.dev",
    "direct": false
  },
  {
    "name": "vite-plugin-pwa",
    "version": "1.3.0",
    "license": "MIT",
    "projectUrl": "https://github.com/vite-pwa/vite-plugin-pwa#readme",
    "direct": true
  }
];

export const GO_DEPS: GoDep[] = [
  {
    "path": "github.com/charmbracelet/bubbles",
    "version": "v1.0.0",
    "indirect": false,
    "license": "MIT",
    "projectUrl": "https://github.com/charmbracelet/bubbles"
  },
  {
    "path": "github.com/charmbracelet/bubbletea",
    "version": "v1.3.10",
    "indirect": false,
    "license": "MIT",
    "projectUrl": "https://github.com/charmbracelet/bubbletea"
  },
  {
    "path": "github.com/charmbracelet/lipgloss",
    "version": "v1.1.0",
    "indirect": false,
    "license": "MIT",
    "projectUrl": "https://github.com/charmbracelet/lipgloss"
  },
  {
    "path": "github.com/coreos/go-systemd/v22",
    "version": "v22.7.0",
    "indirect": false,
    "license": "Apache-2.0",
    "projectUrl": "https://github.com/coreos/go-systemd"
  },
  {
    "path": "github.com/daulet/tokenizers",
    "version": "v1.27.0",
    "indirect": false,
    "license": "MIT",
    "projectUrl": "https://github.com/daulet/tokenizers"
  },
  {
    "path": "github.com/dlclark/regexp2",
    "version": "v1.12.0",
    "indirect": false,
    "license": "MIT",
    "projectUrl": "https://github.com/dlclark/regexp2"
  },
  {
    "path": "github.com/go-webauthn/webauthn",
    "version": "v0.17.4",
    "indirect": false,
    "license": "BSD-3-Clause",
    "projectUrl": "https://github.com/go-webauthn/webauthn"
  },
  {
    "path": "github.com/yalue/onnxruntime_go",
    "version": "v1.34.0",
    "indirect": false,
    "license": "MIT",
    "projectUrl": "https://github.com/yalue/onnxruntime_go"
  },
  {
    "path": "golang.org/x/crypto",
    "version": "v0.54.0",
    "indirect": false,
    "license": "BSD-3-Clause",
    "projectUrl": "https://golang.org/x/crypto"
  },
  {
    "path": "golang.org/x/net",
    "version": "v0.57.0",
    "indirect": false,
    "license": "BSD-3-Clause",
    "projectUrl": "https://golang.org/x/net"
  },
  {
    "path": "golang.org/x/sync",
    "version": "v0.22.0",
    "indirect": false,
    "license": "BSD-3-Clause",
    "projectUrl": "https://golang.org/x/sync"
  },
  {
    "path": "modernc.org/sqlite",
    "version": "v1.38.0",
    "indirect": false,
    "license": "BSD-3-Clause",
    "projectUrl": "https://modernc.org/sqlite"
  },
  {
    "path": "github.com/atotto/clipboard",
    "version": "v0.1.4",
    "indirect": true,
    "license": "BSD-3-Clause",
    "projectUrl": "https://github.com/atotto/clipboard"
  },
  {
    "path": "github.com/aymanbagabas/go-osc52/v2",
    "version": "v2.0.1",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/aymanbagabas/go-osc52"
  },
  {
    "path": "github.com/charmbracelet/colorprofile",
    "version": "v0.4.1",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/charmbracelet/colorprofile"
  },
  {
    "path": "github.com/charmbracelet/x/ansi",
    "version": "v0.11.6",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/charmbracelet/x/ansi"
  },
  {
    "path": "github.com/charmbracelet/x/cellbuf",
    "version": "v0.0.15",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/charmbracelet/x/cellbuf"
  },
  {
    "path": "github.com/charmbracelet/x/term",
    "version": "v0.2.2",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/charmbracelet/x/term"
  },
  {
    "path": "github.com/clipperhouse/displaywidth",
    "version": "v0.9.0",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/clipperhouse/displaywidth"
  },
  {
    "path": "github.com/clipperhouse/stringish",
    "version": "v0.1.1",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/clipperhouse/stringish"
  },
  {
    "path": "github.com/clipperhouse/uax29/v2",
    "version": "v2.5.0",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/clipperhouse/uax29"
  },
  {
    "path": "github.com/dustin/go-humanize",
    "version": "v1.0.1",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/dustin/go-humanize"
  },
  {
    "path": "github.com/erikgeiser/coninput",
    "version": "v0.0.0-20211004153227-1c3628e74d0f",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/erikgeiser/coninput"
  },
  {
    "path": "github.com/fxamacker/cbor/v2",
    "version": "v2.9.2",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/fxamacker/cbor"
  },
  {
    "path": "github.com/go-viper/mapstructure/v2",
    "version": "v2.5.0",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/go-viper/mapstructure"
  },
  {
    "path": "github.com/go-webauthn/x",
    "version": "v0.2.6",
    "indirect": true,
    "license": "BSD-3-Clause",
    "projectUrl": "https://github.com/go-webauthn/x"
  },
  {
    "path": "github.com/godbus/dbus/v5",
    "version": "v5.1.0",
    "indirect": true,
    "license": "BSD-2-Clause",
    "projectUrl": "https://github.com/godbus/dbus"
  },
  {
    "path": "github.com/golang-jwt/jwt/v5",
    "version": "v5.3.1",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/golang-jwt/jwt"
  },
  {
    "path": "github.com/google/go-tpm",
    "version": "v0.9.8",
    "indirect": true,
    "license": "Apache-2.0",
    "projectUrl": "https://github.com/google/go-tpm"
  },
  {
    "path": "github.com/google/uuid",
    "version": "v1.6.0",
    "indirect": true,
    "license": "BSD-3-Clause",
    "projectUrl": "https://github.com/google/uuid"
  },
  {
    "path": "github.com/lucasb-eyer/go-colorful",
    "version": "v1.3.0",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/lucasb-eyer/go-colorful"
  },
  {
    "path": "github.com/mattn/go-isatty",
    "version": "v0.0.20",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/mattn/go-isatty"
  },
  {
    "path": "github.com/mattn/go-localereader",
    "version": "v0.0.1",
    "indirect": true,
    "license": "unknown — needs manual verification",
    "projectUrl": "https://github.com/mattn/go-localereader"
  },
  {
    "path": "github.com/mattn/go-runewidth",
    "version": "v0.0.19",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/mattn/go-runewidth"
  },
  {
    "path": "github.com/muesli/ansi",
    "version": "v0.0.0-20230316100256-276c6243b2f6",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/muesli/ansi"
  },
  {
    "path": "github.com/muesli/cancelreader",
    "version": "v0.2.2",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/muesli/cancelreader"
  },
  {
    "path": "github.com/muesli/termenv",
    "version": "v0.16.0",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/muesli/termenv"
  },
  {
    "path": "github.com/ncruces/go-strftime",
    "version": "v0.1.9",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/ncruces/go-strftime"
  },
  {
    "path": "github.com/philhofer/fwd",
    "version": "v1.2.0",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/philhofer/fwd"
  },
  {
    "path": "github.com/remyoudompheng/bigfft",
    "version": "v0.0.0-20230129092748-24d4a6f8daec",
    "indirect": true,
    "license": "BSD-3-Clause",
    "projectUrl": "https://github.com/remyoudompheng/bigfft"
  },
  {
    "path": "github.com/rivo/uniseg",
    "version": "v0.4.7",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/rivo/uniseg"
  },
  {
    "path": "github.com/tinylib/msgp",
    "version": "v1.6.4",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/tinylib/msgp"
  },
  {
    "path": "github.com/x448/float16",
    "version": "v0.8.4",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/x448/float16"
  },
  {
    "path": "github.com/xo/terminfo",
    "version": "v0.0.0-20220910002029-abceb7e1c41e",
    "indirect": true,
    "license": "MIT",
    "projectUrl": "https://github.com/xo/terminfo"
  },
  {
    "path": "golang.org/x/exp",
    "version": "v0.0.0-20250408133849-7e4ce0ab07d0",
    "indirect": true,
    "license": "BSD-3-Clause",
    "projectUrl": "https://golang.org/x/exp"
  },
  {
    "path": "golang.org/x/sys",
    "version": "v0.47.0",
    "indirect": true,
    "license": "BSD-3-Clause",
    "projectUrl": "https://golang.org/x/sys"
  },
  {
    "path": "golang.org/x/text",
    "version": "v0.40.0",
    "indirect": true,
    "license": "BSD-3-Clause",
    "projectUrl": "https://golang.org/x/text"
  },
  {
    "path": "modernc.org/libc",
    "version": "v1.65.10",
    "indirect": true,
    "license": "BSD-3-Clause",
    "projectUrl": "https://modernc.org/libc"
  },
  {
    "path": "modernc.org/mathutil",
    "version": "v1.7.1",
    "indirect": true,
    "license": "BSD-3-Clause",
    "projectUrl": "https://modernc.org/mathutil"
  },
  {
    "path": "modernc.org/memory",
    "version": "v1.11.0",
    "indirect": true,
    "license": "BSD-3-Clause",
    "projectUrl": "https://modernc.org/memory"
  }
];

// Curated — see gen-attributions.mjs's RUNTIME_STACK. Nothing in this repo
// declares these; they're external processes this app launches or proxies.
export const RUNTIME_STACK: RuntimeComponent[] = [
  {
    "name": "llama.cpp",
    "role": "Local inference engine — every A1–A4 load bay runs llama-server",
    "license": "MIT",
    "projectUrl": "https://github.com/ggml-org/llama.cpp"
  },
  {
    "name": "Qwen3-TTS",
    "role": "Speech synthesis (forge-tts.service, port 8082) — Qwen3-TTS-12Hz-1.7B CustomVoice/VoiceDesign/Base",
    "license": "Apache-2.0",
    "projectUrl": "https://huggingface.co/Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice"
  },
  {
    "name": "Qwen3-Embedding",
    "role": "Always-on CPU embedding service (forge-embedding.service, port 8083) — Qwen3-Embedding-0.6B",
    "license": "Apache-2.0",
    "projectUrl": "https://huggingface.co/Qwen/Qwen3-Embedding-0.6B"
  },
  {
    "name": "parakeet.cpp (Nemotron ASR)",
    "role": "Always-on CPU speech-to-text (forge-stt.service, port 8084) — parakeet.cpp server running nemotron-3.5-asr-streaming-0.6b",
    "license": "MIT (server); OpenMDW-1.1 (model)",
    "projectUrl": "https://github.com/mudler/parakeet.cpp"
  },
  {
    "name": "ComfyUI",
    "role": "Image/video generation backend, managed as a reservation-aware service",
    "license": "GPL-3.0",
    "projectUrl": "https://github.com/comfyanonymous/ComfyUI"
  },
  {
    "name": "vLLM",
    "role": "Inference engine backing the vLLM-style configs (Carbon 8B, Hy-MT2)",
    "license": "Apache-2.0",
    "projectUrl": "https://github.com/vllm-project/vllm"
  }
];
